### ISSUE TITLE
NotFoundError :  _ZN10tensorflow8OpKernel11TraceStringB5cxx11EPNS_15OpKernelContextEb

### ISSUE THREAD

**Issue by starboyvarun** [BIMSBbioinfo/janggu#21]
![4](https://user-images.githubusercontent.com/26819449/130327831-4b73624a-82bd-42c9-b89c-bd8824f8f3fa.JPG)
![4 1](https://user-images.githubusercontent.com/26819449/130327833-84b50f70-5e0a-4751-8109-518709450635.JPG)
![4 2](https://user-images.githubusercontent.com/26819449/130327836-3e8703f3-ac0b-46b2-90d2-ad688240bb45.JPG)

It showed the same version. but when I tried compiling it this time it gave this error.
I haven't found anything about this error anywhere in StackOverflow or any other platform.
Thank you.

**Comment by wkopp** [comment]
This too is an error that is unrelated to janggu. Unfortunately, I am not able to help with this. You might want to redirect your question to the tensorflow repository, if you don't manage to solve it.

**Comment by rekado** [comment]
@starboyvarun This means that libtfkernel_sobol_op.so is not properly linked or you force it use to use an incompatible library.

**Comment by rekado** [comment]
The error says that there's a symbol that libtfkernel_sobol_op.so wants to use but cannot find in any other loaded library.  The symbol should be provided by the tensorflow library.

This is not an error with janggu, so I suggest closing this issue.
