### ISSUE TITLE
syntax Error:

### ISSUE THREAD

**Issue by starboyvarun** [BIMSBbioinfo/janggu#22]
Hello,
Can you please check the below code and let me know what not working. I solved all the past Errors.
![1](https://user-images.githubusercontent.com/26819449/130791293-ef4756ad-d9b3-4114-b61f-7cfa2478ab07.JPG)
![2](https://user-images.githubusercontent.com/26819449/130791310-26103337-b5de-4be1-bf9c-71d18abd3bef.JPG)

**Comment by starboyvarun** [comment]
@wkopp @rekado

**Comment by rekado** [comment]
You're missing a closing parenthesis.
