### ISSUE TITLE
"intersectBed" does not appear to be installed or on the path.

### ISSUE THREAD

**Issue by starboyvarun** [BIMSBbioinfo/janggu#25]
!conda install --yes -c bioconda bedtools samtools
I used the above command and also this below command.
![4](https://user-images.githubusercontent.com/26819449/131207226-54f93322-b50a-41ca-bf00-61de5c475d7e.JPG)
still getting this error.
![4 1](https://user-images.githubusercontent.com/26819449/131207238-b8a31ec0-0432-41c0-91ec-5076558778b3.JPG)

Where will I discover individual bedtools?
Can you tell me how to install bedtools on the path?
Is there any other alternate command for this command: !conda install --yes -c bioconda bedtools samtools
Please don't close the Issue, before my reply.
I read most of the examples there is no installation of bedtools.
Thank you.

**Comment by rekado** [comment]
The directory containing the bedtools binaries must be listed on the PATH environment variable.  You need to put it there by yourself; there's nothing we can do for you to make this happen.

This is not an issue with janggu, so I'm closing the issue.

**Comment by wkopp** [comment]
@starboyvarun , the purpose of the github issues is to inform package developers about bugs/issues of the particular package (in this case the janggu package). It is not a place to post general and unrelated questions to a repository. This includes advice on how to install other software (e.g. samtools), how to use conda, etc. Please do not post issues unrelated to janggu. You can find help about these matters at other places (e.g. the documentation for bedtools or at github repositories for other tools/packages). Thank you.

**Comment by starboyvarun** [comment]
@wkopp Thank you for letting me know.
I already raised the issue with samtools,Bedtools, but they already have pending issues to be resolved. When you told me to raise the issue of tensor flow I raised it there.
I only ask when all doors get closed that's why most issues posted by me come after a day or 2nd day.
Atleast janggu is generous enough to reply to the issues.
Thank you.
