### ISSUE TITLE
NotImplementedError: "intersectBed" does not appear to be installed or on the path, so this method is disabled.  Please install a more recent version of BEDTools and re-import to use this method.

### ISSUE THREAD

**Issue by starboyvarun** [BIMSBbioinfo/janggu#27]
Hello!
I have tried solving this error and even asked for guidance to solve this error in other forums like StackOverflow and biostars.
Been more than 9 days since I posted there but no response. In StackOverflow, this question got +1.
Links to the questions that I have asked has been attached below :
[1.StackOverflow](https://stackoverflow.com/questions/69044165/notimplementederror-intersectbed-does-not-appear-to-be-installed-or-on-the-pa)
[2.Biostars](https://www.biostars.org/p/9487928/#9488296)

Previously you told me to do: "Directory containing the bedtools binaries must be listed on the PATH environment variable"
I have done this

![2 1](https://user-images.githubusercontent.com/26819449/132676409-3aae6f21-bc54-48da-9ebd-b11644304f36.JPG)

![2 2](https://user-images.githubusercontent.com/26819449/132676467-fe41483c-195b-4343-982a-bc5712f9b8a3.JPG)

![2 3](https://user-images.githubusercontent.com/26819449/132676494-a6b803b8-f7e8-4c68-87b0-a0dc0142063f.JPG)

**After, implementing the PATH variable. Still getting this _Error.**

![2 4](https://user-images.githubusercontent.com/26819449/132676516-e78c24e1-d99c-427f-a270-a23978c3a2be.JPG)

![2 5](https://user-images.githubusercontent.com/26819449/132676537-1b7e079e-9a3d-4ec9-8b36-1f818321d0e0.JPG)

To verify that JANGGU installation works I tried to run this example contained in the janggu package as It authenticates. As you can see this example Runs perfectly. 

![2 6](https://user-images.githubusercontent.com/26819449/132677325-3e9b2805-5ce0-4360-af46-99a5e2023621.JPG)

I wanted to implement "Detecting genes from aligned sequencing data"
Can you please tell me what I can do to solve the particular problem I wanted to implement via Google collaborator?
Can I share my Google collab .ipynb notebook link?
I have tried all these days solving this.
Hope to hear from you soon.
Thank You.

**Comment by starboyvarun** [comment]
I am eagerly waiting for your reply @wkopp.
Thank  You.

**Comment by wkopp** [comment]
Did you install bedtools via `apt-get install bedtools`. sys.path.append is not going to work, because bedtools is not a python program. sys.path.append modifies the PYTHONPATH environment variable, but not PATH (see https://docs.python.org/3/tutorial/modules.html). I'm closing this, because it is not a janggu issue. I'm currently on vacation, please excuse my long response time, thanks.

**Comment by starboyvarun** [comment]
@wkopp  Thank you for taking the time to reply on your vacation. I will try my best not to disturb you again.
Thank you so much.
