### ISSUE TITLE
AxisError: axis 2 is out of bounds for array of dimension 2

### ISSUE THREAD

**Issue by starboyvarun** [BIMSBbioinfo/janggu#29]
![1](https://user-images.githubusercontent.com/26819449/133771159-9af8fa7c-fc33-429b-a5d0-a2a4dcd9e1e6.JPG)

![2](https://user-images.githubusercontent.com/26819449/133771167-5ec98dc8-9be5-4133-88fb-6e9f0f02e31b.JPG)

My model runs perfectly.
![3](https://user-images.githubusercontent.com/26819449/133771422-674c5dde-8ed6-48ff-86cd-e3c32399e64c.JPG)

Is something wrong with ReduceDim because when I remove it, this answer comes. Can I do an evaluation with ReduceDim, If yes then can you please tell me how?

![4](https://user-images.githubusercontent.com/26819449/133772001-d095522e-c3f2-458e-87ef-056d4fa91326.JPG)

 Can you please tell me why I am getting AxisError?
 This Error is related to Janggu.
 Thank You.

**Comment by starboyvarun** [comment]
Solved this issue in the previous post.
Thanks.

**Comment by wkopp** [comment]
hi @starboyvarun,

the reason here is also that LABELS was already wrapped with ReduceDim(LABELS) earlier. Wrapping it twice made the dataset incompatible with the neural network model.

**Comment by starboyvarun** [comment]
Hello @wkopp, I understood now.
Thank You.
