### ISSUE TITLE
GenomicIndexer Functionality

### ISSUE THREAD

**Issue by tfabiha** [BIMSBbioinfo/janggu#32]
Hello,

I was wondering if there's an existing way for GenomicIndexer to be automatically generated based on genome size and stepsize? I want to be able to have intervals of size 1000 throughout the genome without having to specify a roi file, but I haven't been able to find anything in the documentation.

**Comment by gaow** [comment]
To echo @tfabiha, indeed it would be very helpful if the DeepSEA and DanQ tutorial can be updated to showing how to annotate every variant in the genome at intervals of 1kb without having to specify regions of interest, just like DeepSEA does. Thanks!

**Comment by wkopp** [comment]
It should be possible to do this by using a pandas dataframe to create a GenomicIndexer.
Here is an example

```
import pandas as pd
from janggu.data import GenomicIndexer

df = pd.DataFrame({'chrom': ['chr1', 'chr2'], 'start': [0, 0], 'end': [10000, 2000]})

gi = GenomicIndexer.create_from_file(df, binsize=1000, stepsize=1000)
