### ISSUE TITLE
README

### ISSUE THREAD

**Issue by remomomo** [BIMSBbioinfo/janggu#7]
I was able to install it in a "fresh" conda environment following your instructions on the main page.

However, I had to make some adjustments. You don't appear to include matplotlib or scikit-learn as dependencies, so I had to install them manually (was getting an error for the proposed test later).

`conda install tensorflow-gpu matplotlib scikit-learn`

Did the trick.

after that there's a small mistake after you clone the repository and switch directories, the command should be

`python ./src/examples/classify_fasta.py single`

**Comment by remomomo** [comment]
also **seaborn** is missing actually

**Comment by wkopp** [comment]
Thanks, for pointing that out. I'll fix this in the next few days.
